/*
 * Apicurio Registry API [v2]
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.5.Final
 * Contact: apicurio@lists.jboss.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.registry.instance.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openshift.cloud.api.registry.instance.models.Error;
import com.openshift.cloud.api.registry.instance.models.RuleViolationCause;
import com.openshift.cloud.api.registry.instance.models.RuleViolationErrorAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * All error responses, whether &#x60;4xx&#x60; or &#x60;5xx&#x60; will include one of these as the response body.
 */
@ApiModel(description = "All error responses, whether `4xx` or `5xx` will include one of these as the response body.")
@JsonPropertyOrder({
  RuleViolationError.JSON_PROPERTY_CAUSES,
  RuleViolationError.JSON_PROPERTY_MESSAGE,
  RuleViolationError.JSON_PROPERTY_ERROR_CODE,
  RuleViolationError.JSON_PROPERTY_DETAIL,
  RuleViolationError.JSON_PROPERTY_NAME
})
@JsonTypeName("RuleViolationError")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RuleViolationError {
  public static final String JSON_PROPERTY_CAUSES = "causes";
  private List<RuleViolationCause> causes = new ArrayList<>();

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_ERROR_CODE = "error_code";
  private Integer errorCode;

  public static final String JSON_PROPERTY_DETAIL = "detail";
  private String detail;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public RuleViolationError() { 
  }

  public RuleViolationError causes(List<RuleViolationCause> causes) {
    
    this.causes = causes;
    return this;
  }

  public RuleViolationError addCausesItem(RuleViolationCause causesItem) {
    this.causes.add(causesItem);
    return this;
  }

   /**
   * List of rule violation causes.
   * @return causes
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "List of rule violation causes.")
  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RuleViolationCause> getCauses() {
    return causes;
  }


  @JsonProperty(JSON_PROPERTY_CAUSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCauses(List<RuleViolationCause> causes) {
    this.causes = causes;
  }


  public RuleViolationError message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * The short error message.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The short error message.")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public RuleViolationError errorCode(Integer errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * The server-side error code.
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The server-side error code.")
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(Integer errorCode) {
    this.errorCode = errorCode;
  }


  public RuleViolationError detail(String detail) {
    
    this.detail = detail;
    return this;
  }

   /**
   * Full details about the error.  This might contain a server stack trace, for example.
   * @return detail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Full details about the error.  This might contain a server stack trace, for example.")
  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDetail() {
    return detail;
  }


  @JsonProperty(JSON_PROPERTY_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetail(String detail) {
    this.detail = detail;
  }


  public RuleViolationError name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The error name - typically the classname of the exception thrown by the server.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The error name - typically the classname of the exception thrown by the server.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuleViolationError ruleViolationError = (RuleViolationError) o;
    return Objects.equals(this.causes, ruleViolationError.causes) &&
        Objects.equals(this.message, ruleViolationError.message) &&
        Objects.equals(this.errorCode, ruleViolationError.errorCode) &&
        Objects.equals(this.detail, ruleViolationError.detail) &&
        Objects.equals(this.name, ruleViolationError.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(causes, message, errorCode, detail, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuleViolationError {\n");
    sb.append("    causes: ").append(toIndentedString(causes)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

