/*
 * Service Accounts API Documentation
 * This is the API documentation for Service Accounts
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.serviceaccounts.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InlineResponse400ResponseLanguage
 */
@JsonPropertyOrder({
  InlineResponse400ResponseLanguage.JSON_PROPERTY_LANGUAGE,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_SCRIPT,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_COUNTRY,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_VARIANT,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_EXTENSION_KEYS,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_UNICODE_LOCALE_ATTRIBUTES,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_UNICODE_LOCALE_KEYS,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_ISO3_LANGUAGE,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_ISO3_COUNTRY,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_DISPLAY_LANGUAGE,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_DISPLAY_SCRIPT,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_DISPLAY_COUNTRY,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_DISPLAY_VARIANT,
  InlineResponse400ResponseLanguage.JSON_PROPERTY_DISPLAY_NAME
})
@JsonTypeName("inline_response_400_response_language")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class InlineResponse400ResponseLanguage {
  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_SCRIPT = "script";
  private String script;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_VARIANT = "variant";
  private String variant;

  public static final String JSON_PROPERTY_EXTENSION_KEYS = "extensionKeys";
  private Set<String> extensionKeys = null;

  public static final String JSON_PROPERTY_UNICODE_LOCALE_ATTRIBUTES = "unicodeLocaleAttributes";
  private Set<String> unicodeLocaleAttributes = null;

  public static final String JSON_PROPERTY_UNICODE_LOCALE_KEYS = "unicodeLocaleKeys";
  private Set<String> unicodeLocaleKeys = null;

  public static final String JSON_PROPERTY_ISO3_LANGUAGE = "iso3Language";
  private String iso3Language;

  public static final String JSON_PROPERTY_ISO3_COUNTRY = "iso3Country";
  private String iso3Country;

  public static final String JSON_PROPERTY_DISPLAY_LANGUAGE = "displayLanguage";
  private String displayLanguage;

  public static final String JSON_PROPERTY_DISPLAY_SCRIPT = "displayScript";
  private String displayScript;

  public static final String JSON_PROPERTY_DISPLAY_COUNTRY = "displayCountry";
  private String displayCountry;

  public static final String JSON_PROPERTY_DISPLAY_VARIANT = "displayVariant";
  private String displayVariant;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public InlineResponse400ResponseLanguage() { 
  }

  public InlineResponse400ResponseLanguage language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public InlineResponse400ResponseLanguage script(String script) {
    
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getScript() {
    return script;
  }


  @JsonProperty(JSON_PROPERTY_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScript(String script) {
    this.script = script;
  }


  public InlineResponse400ResponseLanguage country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(String country) {
    this.country = country;
  }


  public InlineResponse400ResponseLanguage variant(String variant) {
    
    this.variant = variant;
    return this;
  }

   /**
   * Get variant
   * @return variant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVariant() {
    return variant;
  }


  @JsonProperty(JSON_PROPERTY_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariant(String variant) {
    this.variant = variant;
  }


  public InlineResponse400ResponseLanguage extensionKeys(Set<String> extensionKeys) {
    
    this.extensionKeys = extensionKeys;
    return this;
  }

  public InlineResponse400ResponseLanguage addExtensionKeysItem(String extensionKeysItem) {
    if (this.extensionKeys == null) {
      this.extensionKeys = new LinkedHashSet<>();
    }
    this.extensionKeys.add(extensionKeysItem);
    return this;
  }

   /**
   * Get extensionKeys
   * @return extensionKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTENSION_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getExtensionKeys() {
    return extensionKeys;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_EXTENSION_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtensionKeys(Set<String> extensionKeys) {
    this.extensionKeys = extensionKeys;
  }


  public InlineResponse400ResponseLanguage unicodeLocaleAttributes(Set<String> unicodeLocaleAttributes) {
    
    this.unicodeLocaleAttributes = unicodeLocaleAttributes;
    return this;
  }

  public InlineResponse400ResponseLanguage addUnicodeLocaleAttributesItem(String unicodeLocaleAttributesItem) {
    if (this.unicodeLocaleAttributes == null) {
      this.unicodeLocaleAttributes = new LinkedHashSet<>();
    }
    this.unicodeLocaleAttributes.add(unicodeLocaleAttributesItem);
    return this;
  }

   /**
   * Get unicodeLocaleAttributes
   * @return unicodeLocaleAttributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNICODE_LOCALE_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getUnicodeLocaleAttributes() {
    return unicodeLocaleAttributes;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_UNICODE_LOCALE_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnicodeLocaleAttributes(Set<String> unicodeLocaleAttributes) {
    this.unicodeLocaleAttributes = unicodeLocaleAttributes;
  }


  public InlineResponse400ResponseLanguage unicodeLocaleKeys(Set<String> unicodeLocaleKeys) {
    
    this.unicodeLocaleKeys = unicodeLocaleKeys;
    return this;
  }

  public InlineResponse400ResponseLanguage addUnicodeLocaleKeysItem(String unicodeLocaleKeysItem) {
    if (this.unicodeLocaleKeys == null) {
      this.unicodeLocaleKeys = new LinkedHashSet<>();
    }
    this.unicodeLocaleKeys.add(unicodeLocaleKeysItem);
    return this;
  }

   /**
   * Get unicodeLocaleKeys
   * @return unicodeLocaleKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNICODE_LOCALE_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<String> getUnicodeLocaleKeys() {
    return unicodeLocaleKeys;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_UNICODE_LOCALE_KEYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnicodeLocaleKeys(Set<String> unicodeLocaleKeys) {
    this.unicodeLocaleKeys = unicodeLocaleKeys;
  }


  public InlineResponse400ResponseLanguage iso3Language(String iso3Language) {
    
    this.iso3Language = iso3Language;
    return this;
  }

   /**
   * Get iso3Language
   * @return iso3Language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO3_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso3Language() {
    return iso3Language;
  }


  @JsonProperty(JSON_PROPERTY_ISO3_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso3Language(String iso3Language) {
    this.iso3Language = iso3Language;
  }


  public InlineResponse400ResponseLanguage iso3Country(String iso3Country) {
    
    this.iso3Country = iso3Country;
    return this;
  }

   /**
   * Get iso3Country
   * @return iso3Country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ISO3_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIso3Country() {
    return iso3Country;
  }


  @JsonProperty(JSON_PROPERTY_ISO3_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso3Country(String iso3Country) {
    this.iso3Country = iso3Country;
  }


  public InlineResponse400ResponseLanguage displayLanguage(String displayLanguage) {
    
    this.displayLanguage = displayLanguage;
    return this;
  }

   /**
   * Get displayLanguage
   * @return displayLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayLanguage() {
    return displayLanguage;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayLanguage(String displayLanguage) {
    this.displayLanguage = displayLanguage;
  }


  public InlineResponse400ResponseLanguage displayScript(String displayScript) {
    
    this.displayScript = displayScript;
    return this;
  }

   /**
   * Get displayScript
   * @return displayScript
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayScript() {
    return displayScript;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayScript(String displayScript) {
    this.displayScript = displayScript;
  }


  public InlineResponse400ResponseLanguage displayCountry(String displayCountry) {
    
    this.displayCountry = displayCountry;
    return this;
  }

   /**
   * Get displayCountry
   * @return displayCountry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayCountry() {
    return displayCountry;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayCountry(String displayCountry) {
    this.displayCountry = displayCountry;
  }


  public InlineResponse400ResponseLanguage displayVariant(String displayVariant) {
    
    this.displayVariant = displayVariant;
    return this;
  }

   /**
   * Get displayVariant
   * @return displayVariant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayVariant() {
    return displayVariant;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_VARIANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayVariant(String displayVariant) {
    this.displayVariant = displayVariant;
  }


  public InlineResponse400ResponseLanguage displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse400ResponseLanguage inlineResponse400ResponseLanguage = (InlineResponse400ResponseLanguage) o;
    return Objects.equals(this.language, inlineResponse400ResponseLanguage.language) &&
        Objects.equals(this.script, inlineResponse400ResponseLanguage.script) &&
        Objects.equals(this.country, inlineResponse400ResponseLanguage.country) &&
        Objects.equals(this.variant, inlineResponse400ResponseLanguage.variant) &&
        Objects.equals(this.extensionKeys, inlineResponse400ResponseLanguage.extensionKeys) &&
        Objects.equals(this.unicodeLocaleAttributes, inlineResponse400ResponseLanguage.unicodeLocaleAttributes) &&
        Objects.equals(this.unicodeLocaleKeys, inlineResponse400ResponseLanguage.unicodeLocaleKeys) &&
        Objects.equals(this.iso3Language, inlineResponse400ResponseLanguage.iso3Language) &&
        Objects.equals(this.iso3Country, inlineResponse400ResponseLanguage.iso3Country) &&
        Objects.equals(this.displayLanguage, inlineResponse400ResponseLanguage.displayLanguage) &&
        Objects.equals(this.displayScript, inlineResponse400ResponseLanguage.displayScript) &&
        Objects.equals(this.displayCountry, inlineResponse400ResponseLanguage.displayCountry) &&
        Objects.equals(this.displayVariant, inlineResponse400ResponseLanguage.displayVariant) &&
        Objects.equals(this.displayName, inlineResponse400ResponseLanguage.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, script, country, variant, extensionKeys, unicodeLocaleAttributes, unicodeLocaleKeys, iso3Language, iso3Country, displayLanguage, displayScript, displayCountry, displayVariant, displayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse400ResponseLanguage {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    variant: ").append(toIndentedString(variant)).append("\n");
    sb.append("    extensionKeys: ").append(toIndentedString(extensionKeys)).append("\n");
    sb.append("    unicodeLocaleAttributes: ").append(toIndentedString(unicodeLocaleAttributes)).append("\n");
    sb.append("    unicodeLocaleKeys: ").append(toIndentedString(unicodeLocaleKeys)).append("\n");
    sb.append("    iso3Language: ").append(toIndentedString(iso3Language)).append("\n");
    sb.append("    iso3Country: ").append(toIndentedString(iso3Country)).append("\n");
    sb.append("    displayLanguage: ").append(toIndentedString(displayLanguage)).append("\n");
    sb.append("    displayScript: ").append(toIndentedString(displayScript)).append("\n");
    sb.append("    displayCountry: ").append(toIndentedString(displayCountry)).append("\n");
    sb.append("    displayVariant: ").append(toIndentedString(displayVariant)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

