/*
 * Kafka Management API
 * Kafka Management API is a REST API to manage Kafka instances
 *
 * The version of the OpenAPI document: 1.16.0
 * Contact: rhosak-support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.kas.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openshift.cloud.api.kas.models.EnterpriseCluster;
import com.openshift.cloud.api.kas.models.EnterpriseClusterAllOfCapacityInformation;
import com.openshift.cloud.api.kas.models.EnterpriseClusterFleetshardParameters;
import com.openshift.cloud.api.kas.models.FleetshardParameter;
import com.openshift.cloud.api.kas.models.SupportedKafkaInstanceTypesList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Enterprise Cluster registration response. It returns additional privileged information compared to The information returned by EnterpriseCluster
 */
@ApiModel(description = "Enterprise Cluster registration response. It returns additional privileged information compared to The information returned by EnterpriseCluster")
@JsonPropertyOrder({
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_ID,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_KIND,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_HREF,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_ACCESS_KAFKAS_VIA_PRIVATE_NETWORK,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_CLUSTER_ID,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_STATUS,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_CLOUD_PROVIDER,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_REGION,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_MULTI_AZ,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_SUPPORTED_INSTANCE_TYPES,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_CAPACITY_INFORMATION,
  EnterpriseClusterRegistrationResponse.JSON_PROPERTY_FLEETSHARD_PARAMETERS
})
@JsonTypeName("EnterpriseClusterRegistrationResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EnterpriseClusterRegistrationResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_KIND = "kind";
  private String kind;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  public static final String JSON_PROPERTY_ACCESS_KAFKAS_VIA_PRIVATE_NETWORK = "access_kafkas_via_private_network";
  private Boolean accessKafkasViaPrivateNetwork;

  public static final String JSON_PROPERTY_CLUSTER_ID = "cluster_id";
  private String clusterId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_CLOUD_PROVIDER = "cloud_provider";
  private String cloudProvider;

  public static final String JSON_PROPERTY_REGION = "region";
  private String region;

  public static final String JSON_PROPERTY_MULTI_AZ = "multi_az";
  private Boolean multiAz;

  public static final String JSON_PROPERTY_SUPPORTED_INSTANCE_TYPES = "supported_instance_types";
  private SupportedKafkaInstanceTypesList supportedInstanceTypes;

  public static final String JSON_PROPERTY_CAPACITY_INFORMATION = "capacity_information";
  private EnterpriseClusterAllOfCapacityInformation capacityInformation;

  public static final String JSON_PROPERTY_FLEETSHARD_PARAMETERS = "fleetshard_parameters";
  private List<FleetshardParameter> fleetshardParameters = null;

  public EnterpriseClusterRegistrationResponse() { 
  }

  public EnterpriseClusterRegistrationResponse id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public EnterpriseClusterRegistrationResponse kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKind() {
    return kind;
  }


  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKind(String kind) {
    this.kind = kind;
  }


  public EnterpriseClusterRegistrationResponse href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHref(String href) {
    this.href = href;
  }


  public EnterpriseClusterRegistrationResponse accessKafkasViaPrivateNetwork(Boolean accessKafkasViaPrivateNetwork) {
    
    this.accessKafkasViaPrivateNetwork = accessKafkasViaPrivateNetwork;
    return this;
  }

   /**
   * Indicates whether Kafkas created on this data plane cluster have to be accessed via private network
   * @return accessKafkasViaPrivateNetwork
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Indicates whether Kafkas created on this data plane cluster have to be accessed via private network")
  @JsonProperty(JSON_PROPERTY_ACCESS_KAFKAS_VIA_PRIVATE_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAccessKafkasViaPrivateNetwork() {
    return accessKafkasViaPrivateNetwork;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_KAFKAS_VIA_PRIVATE_NETWORK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessKafkasViaPrivateNetwork(Boolean accessKafkasViaPrivateNetwork) {
    this.accessKafkasViaPrivateNetwork = accessKafkasViaPrivateNetwork;
  }


  public EnterpriseClusterRegistrationResponse clusterId(String clusterId) {
    
    this.clusterId = clusterId;
    return this;
  }

   /**
   * The OCM&#39;s cluster id of the registered Enterprise cluster.
   * @return clusterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The OCM's cluster id of the registered Enterprise cluster.")
  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClusterId() {
    return clusterId;
  }


  @JsonProperty(JSON_PROPERTY_CLUSTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }


  public EnterpriseClusterRegistrationResponse status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of Enterprise cluster registration
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of Enterprise cluster registration")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public EnterpriseClusterRegistrationResponse cloudProvider(String cloudProvider) {
    
    this.cloudProvider = cloudProvider;
    return this;
  }

   /**
   * The cloud provider for this cluster. This valus will be used as the Kafka&#39;s cloud provider value when a Kafka is created on this cluster
   * @return cloudProvider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The cloud provider for this cluster. This valus will be used as the Kafka's cloud provider value when a Kafka is created on this cluster")
  @JsonProperty(JSON_PROPERTY_CLOUD_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCloudProvider() {
    return cloudProvider;
  }


  @JsonProperty(JSON_PROPERTY_CLOUD_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCloudProvider(String cloudProvider) {
    this.cloudProvider = cloudProvider;
  }


  public EnterpriseClusterRegistrationResponse region(String region) {
    
    this.region = region;
    return this;
  }

   /**
   * The region of this cluster. This valus will be used as the Kafka&#39;s region value when a Kafka is created on this cluster
   * @return region
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The region of this cluster. This valus will be used as the Kafka's region value when a Kafka is created on this cluster")
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegion(String region) {
    this.region = region;
  }


  public EnterpriseClusterRegistrationResponse multiAz(Boolean multiAz) {
    
    this.multiAz = multiAz;
    return this;
  }

   /**
   * A flag indicating whether this cluster is available on multiple availability zones or not
   * @return multiAz
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A flag indicating whether this cluster is available on multiple availability zones or not")
  @JsonProperty(JSON_PROPERTY_MULTI_AZ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMultiAz() {
    return multiAz;
  }


  @JsonProperty(JSON_PROPERTY_MULTI_AZ)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMultiAz(Boolean multiAz) {
    this.multiAz = multiAz;
  }


  public EnterpriseClusterRegistrationResponse supportedInstanceTypes(SupportedKafkaInstanceTypesList supportedInstanceTypes) {
    
    this.supportedInstanceTypes = supportedInstanceTypes;
    return this;
  }

   /**
   * Get supportedInstanceTypes
   * @return supportedInstanceTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPORTED_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SupportedKafkaInstanceTypesList getSupportedInstanceTypes() {
    return supportedInstanceTypes;
  }


  @JsonProperty(JSON_PROPERTY_SUPPORTED_INSTANCE_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupportedInstanceTypes(SupportedKafkaInstanceTypesList supportedInstanceTypes) {
    this.supportedInstanceTypes = supportedInstanceTypes;
  }


  public EnterpriseClusterRegistrationResponse capacityInformation(EnterpriseClusterAllOfCapacityInformation capacityInformation) {
    
    this.capacityInformation = capacityInformation;
    return this;
  }

   /**
   * Get capacityInformation
   * @return capacityInformation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAPACITY_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnterpriseClusterAllOfCapacityInformation getCapacityInformation() {
    return capacityInformation;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacityInformation(EnterpriseClusterAllOfCapacityInformation capacityInformation) {
    this.capacityInformation = capacityInformation;
  }


  public EnterpriseClusterRegistrationResponse fleetshardParameters(List<FleetshardParameter> fleetshardParameters) {
    
    this.fleetshardParameters = fleetshardParameters;
    return this;
  }

  public EnterpriseClusterRegistrationResponse addFleetshardParametersItem(FleetshardParameter fleetshardParametersItem) {
    if (this.fleetshardParameters == null) {
      this.fleetshardParameters = new ArrayList<>();
    }
    this.fleetshardParameters.add(fleetshardParametersItem);
    return this;
  }

   /**
   * Enterprise Cluster fleetshard parameters array
   * @return fleetshardParameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enterprise Cluster fleetshard parameters array")
  @JsonProperty(JSON_PROPERTY_FLEETSHARD_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FleetshardParameter> getFleetshardParameters() {
    return fleetshardParameters;
  }


  @JsonProperty(JSON_PROPERTY_FLEETSHARD_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFleetshardParameters(List<FleetshardParameter> fleetshardParameters) {
    this.fleetshardParameters = fleetshardParameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseClusterRegistrationResponse enterpriseClusterRegistrationResponse = (EnterpriseClusterRegistrationResponse) o;
    return Objects.equals(this.id, enterpriseClusterRegistrationResponse.id) &&
        Objects.equals(this.kind, enterpriseClusterRegistrationResponse.kind) &&
        Objects.equals(this.href, enterpriseClusterRegistrationResponse.href) &&
        Objects.equals(this.accessKafkasViaPrivateNetwork, enterpriseClusterRegistrationResponse.accessKafkasViaPrivateNetwork) &&
        Objects.equals(this.clusterId, enterpriseClusterRegistrationResponse.clusterId) &&
        Objects.equals(this.status, enterpriseClusterRegistrationResponse.status) &&
        Objects.equals(this.cloudProvider, enterpriseClusterRegistrationResponse.cloudProvider) &&
        Objects.equals(this.region, enterpriseClusterRegistrationResponse.region) &&
        Objects.equals(this.multiAz, enterpriseClusterRegistrationResponse.multiAz) &&
        Objects.equals(this.supportedInstanceTypes, enterpriseClusterRegistrationResponse.supportedInstanceTypes) &&
        Objects.equals(this.capacityInformation, enterpriseClusterRegistrationResponse.capacityInformation) &&
        Objects.equals(this.fleetshardParameters, enterpriseClusterRegistrationResponse.fleetshardParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kind, href, accessKafkasViaPrivateNetwork, clusterId, status, cloudProvider, region, multiAz, supportedInstanceTypes, capacityInformation, fleetshardParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseClusterRegistrationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    accessKafkasViaPrivateNetwork: ").append(toIndentedString(accessKafkasViaPrivateNetwork)).append("\n");
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    cloudProvider: ").append(toIndentedString(cloudProvider)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    multiAz: ").append(toIndentedString(multiAz)).append("\n");
    sb.append("    supportedInstanceTypes: ").append(toIndentedString(supportedInstanceTypes)).append("\n");
    sb.append("    capacityInformation: ").append(toIndentedString(capacityInformation)).append("\n");
    sb.append("    fleetshardParameters: ").append(toIndentedString(fleetshardParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

