/*
 * Kafka Admin REST API
 * An API to provide REST endpoints for query Kafka for admin operations
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.kas.auth.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.openshift.cloud.api.kas.auth.models.ConsumerGroupResetOffsetResultItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RootTypeForConsumerGroupResetOffsetResult
 */
@JsonPropertyOrder({
  RootTypeForConsumerGroupResetOffsetResult.JSON_PROPERTY_ITEMS
})
@JsonTypeName("Root_Type_for_ConsumerGroupResetOffsetResult")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RootTypeForConsumerGroupResetOffsetResult {
  public static final String JSON_PROPERTY_ITEMS = "items";
  private List<ConsumerGroupResetOffsetResultItem> items = null;

  public RootTypeForConsumerGroupResetOffsetResult() { 
  }

  public RootTypeForConsumerGroupResetOffsetResult items(List<ConsumerGroupResetOffsetResultItem> items) {
    
    this.items = items;
    return this;
  }

  public RootTypeForConsumerGroupResetOffsetResult addItemsItem(ConsumerGroupResetOffsetResultItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConsumerGroupResetOffsetResultItem> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setItems(List<ConsumerGroupResetOffsetResultItem> items) {
    this.items = items;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootTypeForConsumerGroupResetOffsetResult rootTypeForConsumerGroupResetOffsetResult = (RootTypeForConsumerGroupResetOffsetResult) o;
    return Objects.equals(this.items, rootTypeForConsumerGroupResetOffsetResult.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootTypeForConsumerGroupResetOffsetResult {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

