/*
 * Red Hat Openshift SmartEvents Fleet Manager V2
 * The API exposed by the fleet manager of the SmartEvents service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: openbridge-dev@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.openshift.cloud.api.smartevents.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ManagedResourceStatus
 */
public enum ManagedResourceStatus {
  
  ACCEPTED("accepted"),
  
  PREPARING("preparing"),
  
  PROVISIONING("provisioning"),
  
  READY("ready"),
  
  UPDATE_ACCEPTED("update_accepted"),
  
  UPDATE_PREPARING("update_preparing"),
  
  UPDATE_PROVISIONING("update_provisioning"),
  
  DEPROVISION("deprovision"),
  
  DELETING("deleting"),
  
  DELETED("deleted"),
  
  FAILED("failed");

  private String value;

  ManagedResourceStatus(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ManagedResourceStatus fromValue(String value) {
    for (ManagedResourceStatus b : ManagedResourceStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

