name: Generate API clients
on:
  push:
    branches:
      - main
    paths:
      - ".openapi/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js  
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: mkdir -p "$HOME/.local/bin"; echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O $HOME/.local/bin/yq && chmod +x $HOME/.local/bin/yq          
      - name: Generate API clients
        run: ./scripts/generate.sh
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "chore(all): re-generate OpenAPI client(s)"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: "chore(all): re-generate OpenAPI client(s)"
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: chore/generate-api-clients
          branch-suffix: timestamp
          reviewers: craicoverflow, wtrocki, CI_USER_TOKEN
          delete-branch: suffix
          body: |
            _This pull request was auto-generated_

            This PR adds the latest generated API clients.

            **Actions**:

              1. Review changes and validate against the examples.
              2. Make changes where necessary.
              3. Approve and merge with proper commit message tha represents change
              4. Create a release.
